---

version: '3.5'
services:
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-4.2.3
    container_name: zabbix_web
    #Just for debug
    #volumes:
    #  - ../logs/nginx/:/var/log/nginx/
    #  - ../logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
    networks:
      zabbix-net:
        aliases:
          # Hostname for embedded Docker DNS services 127.0.0.11
          - zabbix-web
    ports:
      # Web UI port
      # I prefer just expose. Please use a proxy (for example HAproxy)
      - 8888:80
      # Active agents requests zabbix on port
      #- 10051:10051
    depends_on:
      - zabbix-mysql
      - zabbix-server
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=correct_horse_battery_staple
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_NAME=Visiblenameforthemainwebsite
      - ZBX_SERVER_HOST=zabbix-server
      #- PHP_TZ=Europe/Budapest
    restart: always

  zabbix-server:
    image: d3vm/zabbix-slack:latest
    container_name: zabbix_server
    networks:
      zabbix-net:
        aliases:
          # Hostname for embedded Docker DNS services 127.0.0.11
          - zabbix-server
    depends_on:
      - zabbix-mysql
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=correct_horse_battery_staple
      - MYSQL_DATABASE=zabbix
    restart: always
  
  zabbix-mysql:
    image: mariadb:10.4.6-bionic
    container_name: zabbix_mysql
    networks:
      zabbix-net:
        aliases:
          # Hostname for embedded Docker DNS services 127.0.0.11
          - zabbix-mysql
    volumes:
      - ../vars/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=correct_horse_battery_staple
    restart: always

networks:
  zabbix-net:
    external: true